SELECT  A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM    BOOK A, AUTHOR B,
(SELECT  BOOK_ID, SALES
FROM    BOOK_SALES
WHERE   EXTRACT(YEAR FROM SALES_DATE) = 2022 AND EXTRACT (MONTH FROM SALES_DATE) = 1) C
WHERE   A.BOOK_ID = C.BOOK_ID
  AND   A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC 