-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, B.CITY||' '|| B.STREET_ADDRESS1 ||' '|| B.STREET_ADDRESS2 AS "전체주소", SUBSTR(B.TLNO,0,3)||'-'||SUBSTR(B.TLNO,4,4)||'-'||SUBSTR(B.TLNO,8) AS "전화번호"
FROM USED_GOODS_BOARD A, USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID
GROUP BY B.USER_ID, B.NICKNAME, B.STREET_ADDRESS1, B.STREET_ADDRESS2, B.TLNO, B.CITY
HAVING COUNT(*) >= 3
ORDER BY USER_ID DESC