-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, AVG(B.REVIEW_SCORE)
FROM REST_INFO A, REST_REVIEW B
WHERE A.REST_ID = B.REST_ID AND A.ADDRESS LIKE ('%서울특별시%')
GROUP BY A.REST_ID
ORDER BY AVG(B.REVIEW_SCORE) DESC, A.FAVORITES DESC