-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, T.SCORE
FROM REST_INFO A, (
    SELECT B.REST_ID, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW B
    GROUP BY B.REST_ID) T
WHERE A.REST_ID = T.REST_ID AND A.ADDRESS LIKE ('서울%')      
ORDER BY T.SCORE DESC, A.FAVORITES DESC