-- 코드를 입력하세요


SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM (
SELECT EXTRACT(YEAR FROM ONLINE_SALE.SALES_DATE) AS YEAR, EXTRACT(MONTH FROM ONLINE_SALE.SALES_DATE) AS MONTH, USER_INFO.GENDER, COUNT(*) AS USERS
FROM USER_INFO, ONLINE_SALE
WHERE USER_INFO.USER_ID = ONLINE_SALE.USER_ID
GROUP BY EXTRACT(YEAR FROM ONLINE_SALE.SALES_DATE), EXTRACT(MONTH FROM ONLINE_SALE.SALES_DATE), USER_INFO.USER_ID, USER_INFO.GENDER
HAVING USER_INFO.GENDER IS NOT NULL
)
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1,2,3 ASC

