-- 코드를 입력하세요
SELECT F.PRODUCT_ID, P.PRODUCT_NAME, SUM(F.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER F, FOOD_PRODUCT P
WHERE F.PRODUCT_ID = P.PRODUCT_ID AND EXTRACT(YEAR FROM F.PRODUCE_DATE) = 2022 AND EXTRACT(MONTH FROM F.PRODUCE_DATE) = 5
GROUP BY F.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID ASC