-- 코드를 입력하세요
SELECT HISTORY_ID, CASE WHEN DISCOUNT_RATE IS NOT NULL THEN 
(DAILY_FEE * DURATION) * ((100 - DISCOUNT_RATE) / 100) ELSE (DAILY_FEE * DURATION) END AS FEE
FROM (SELECT B.HISTORY_ID, 
      CASE WHEN B.END_DATE - B.START_DATE +1 >= 90 THEN '90일 이상' 
      WHEN B.END_DATE - B.START_DATE+1 >= 30 THEN '30일 이상' 
      WHEN B.END_DATE - B.START_DATE + 1 >= 7 THEN '7일 이상' 
      ELSE NULL END AS DURATION_TYPE, 
      A.DAILY_FEE,
      B.END_DATE - B.START_DATE + 1 AS DURATION,
      A.CAR_TYPE
      FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
     WHERE A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = '트럭') A LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
     ON A.DURATION_TYPE = C.DURATION_TYPE AND A.CAR_TYPE = C.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC