-- 코드를 입력하세요



SELECT B.HOUR, NVL(A.COUNT, 0) AS COUNT
FROM 
 (SELECT (LEVEL-1) AS HOUR
        FROM DUAL CONNECT BY LEVEL <= 24) B LEFT OUTER JOIN (SELECT TO_CHAR(DATETIME, 'hh24') AS "HOUR", COUNT(*) AS "COUNT" 
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'hh24')
ORDER BY "HOUR") A ON A.HOUR = B.HOUR
ORDER BY B.HOUR