-- 코드를 입력하세요
SELECT WRITER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM (
    SELECT A.WRITER_ID, B.NICKNAME, A.PRICE
    FROM USED_GOODS_BOARD A, USED_GOODS_USER B
    WHERE A.WRITER_ID = B.USER_ID AND A.STATUS = 'DONE' 
)
GROUP BY WRITER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES