-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD')
FROM (SELECT B.MEMBER_NAME, C.REVIEW_TEXT, C.REVIEW_DATE, RANK() OVER(ORDER BY CNT DESC) AS RANKS
FROM (
SELECT MEMBER_ID, COUNT(*) AS CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY CNT DESC ) A, MEMBER_PROFILE B, REST_REVIEW C
WHERE A.MEMBER_ID = B.MEMBER_ID AND A.MEMBER_ID = C.MEMBER_ID )
WHERE RANKS = 1 
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC