-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM (
    SELECT A.TOTAL_ORDER, B.INGREDIENT_TYPE
    FROM FIRST_HALF A, ICECREAM_INFO B
    WHERE A.FLAVOR = B.FLAVOR
)
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC
