-- 코드를 입력하세요
SELECT FILE_PATH
FROM (SELECT A.FILE_ID, '/home/grep/src/'||A.BOARD_ID||'/'||A.FILE_ID||A.FILE_NAME||A.FILE_EXT AS FILE_PATH, RANK() OVER(ORDER BY B.VIEWS DESC) AS RANKS
FROM USED_GOODS_FILE A, USED_GOODS_BOARD B
WHERE A.BOARD_ID = B.BOARD_ID) 
WHERE RANKS = 1
ORDER BY FILE_ID DESC